POST http://localhost:8080/create-monster
Content-Type: application/json

{
  "monsterLevel": "BABY",
  "monsterType": "GROUND",
  "statusCode": "HEALTHY",
  "ssn": "1132561532567",
  "name": "file_dog",
  "age": 0,
  "height": 153,
  "weight" : 57

}